# Generated by Django 4.2.5 on 2023-10-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('no_of_teams', models.IntegerField()),
                ('no_of_goals', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
